[2023-12-28T04:27:03.004+0000] {processor.py:161} INFO - Started process (PID=41123) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:27:03.009+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:03.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.068+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:03.048+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:27:03.070+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:03.939+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.943 seconds
[2023-12-28T04:27:34.395+0000] {processor.py:161} INFO - Started process (PID=41179) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.397+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:27:34.398+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:34.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.416+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:27:34.414+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:27:34.417+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:27:34.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.056 seconds
[2023-12-28T04:28:05.025+0000] {processor.py:161} INFO - Started process (PID=41235) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.030+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:28:05.032+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:05.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.077+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:05.075+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:28:05.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:05.285+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.265 seconds
[2023-12-28T04:28:35.402+0000] {processor.py:161} INFO - Started process (PID=41291) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.405+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:28:35.408+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:35.407+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.444+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:28:35.441+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:28:35.446+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:28:35.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.096 seconds
[2023-12-28T04:29:08.661+0000] {processor.py:161} INFO - Started process (PID=41330) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:29:08.667+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:08.667+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.698+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:08.695+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:29:08.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:08.849+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.196 seconds
[2023-12-28T04:29:39.061+0000] {processor.py:161} INFO - Started process (PID=41387) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:29:39.095+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:39.095+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.189+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:29:39.186+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:29:39.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:29:39.458+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.405 seconds
[2023-12-28T04:30:09.516+0000] {processor.py:161} INFO - Started process (PID=41443) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:30:09.541+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:09.541+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.580+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:09.573+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:30:09.581+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:09.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.132 seconds
[2023-12-28T04:30:39.912+0000] {processor.py:161} INFO - Started process (PID=41496) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:39.925+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:30:39.926+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:39.926+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:40.033+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:30:40.010+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:30:40.035+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:30:40.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.348 seconds
[2023-12-28T04:31:11.130+0000] {processor.py:161} INFO - Started process (PID=41552) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.133+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:31:11.135+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:11.134+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.162+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:11.160+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:31:11.163+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:11.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.078 seconds
[2023-12-28T04:31:41.249+0000] {processor.py:161} INFO - Started process (PID=41608) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:31:41.253+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:41.252+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.271+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:31:41.270+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:31:41.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:31:41.299+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.055 seconds
[2023-12-28T04:32:11.429+0000] {processor.py:161} INFO - Started process (PID=41663) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:32:11.435+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:11.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.465+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:11.463+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:32:11.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:11.522+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.099 seconds
[2023-12-28T04:32:41.837+0000] {processor.py:161} INFO - Started process (PID=41719) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:41.854+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:32:41.857+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:41.856+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:42.869+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:32:41.961+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:32:42.874+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:32:42.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.122 seconds
[2023-12-28T04:33:13.343+0000] {processor.py:161} INFO - Started process (PID=41769) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.366+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:33:13.368+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:13.367+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.415+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:13.400+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:33:13.416+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:13.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.185 seconds
[2023-12-28T04:33:44.567+0000] {processor.py:161} INFO - Started process (PID=41821) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:33:44.584+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:44.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.662+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:33:44.660+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:33:44.664+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:33:44.840+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.281 seconds
[2023-12-28T04:34:15.152+0000] {processor.py:161} INFO - Started process (PID=41875) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:34:15.169+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:15.169+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.231+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:15.220+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:34:15.232+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:15.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.395 seconds
[2023-12-28T04:34:48.778+0000] {processor.py:161} INFO - Started process (PID=41931) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:48.780+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:34:48.782+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:48.781+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:49.079+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:34:48.815+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:34:49.080+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:34:49.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.639 seconds
[2023-12-28T04:35:19.894+0000] {processor.py:161} INFO - Started process (PID=41987) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.897+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:35:19.899+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:19.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.923+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:19.920+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 7
    catchup=False) as dag:
                         ^
SyntaxError: unexpected EOF while parsing
[2023-12-28T04:35:19.924+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:19.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.073 seconds
[2023-12-28T04:35:32.156+0000] {processor.py:161} INFO - Started process (PID=42023) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:35:32.159+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:32.159+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.205+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:35:32.198+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:35:32.207+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:35:32.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2023-12-28T04:36:02.795+0000] {processor.py:161} INFO - Started process (PID=42072) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:02.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:02.809+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:02.808+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:03.383+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:02.862+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:03.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:03.513+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.731 seconds
[2023-12-28T04:36:05.257+0000] {processor.py:161} INFO - Started process (PID=42079) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.260+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:05.264+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:05.262+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.342+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:05.332+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:05.345+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:05.400+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.153 seconds
[2023-12-28T04:36:35.968+0000] {processor.py:161} INFO - Started process (PID=42128) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.007+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:36:36.009+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:36.008+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.159+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:36:36.080+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:36:36.164+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:36:36.315+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.354 seconds
[2023-12-28T04:37:16.236+0000] {processor.py:161} INFO - Started process (PID=42161) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:37:16.247+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:16.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.391+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:16.289+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:37:16.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:16.929+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.701 seconds
[2023-12-28T04:37:47.324+0000] {processor.py:161} INFO - Started process (PID=42218) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:37:47.327+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:47.327+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.382+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:37:47.369+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:37:47.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:37:47.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.103 seconds
[2023-12-28T04:38:18.132+0000] {processor.py:161} INFO - Started process (PID=42274) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.142+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:18.144+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:18.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.211+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:18.202+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:18.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:18.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.125 seconds
[2023-12-28T04:38:28.384+0000] {processor.py:161} INFO - Started process (PID=42287) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.385+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:28.386+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:28.386+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.422+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:28.418+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:28.424+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:28.452+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2023-12-28T04:38:47.683+0000] {processor.py:161} INFO - Started process (PID=42324) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:38:47.687+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:47.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.744+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:38:47.737+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:38:47.748+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:38:47.796+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.120 seconds
[2023-12-28T04:39:18.737+0000] {processor.py:161} INFO - Started process (PID=42380) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.739+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:39:18.742+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:18.740+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.807+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:18.792+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:39:18.811+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:18.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.124 seconds
[2023-12-28T04:39:49.000+0000] {processor.py:161} INFO - Started process (PID=42436) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:39:49.003+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:49.002+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.053+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:39:49.046+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:39:49.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:39:49.148+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.151 seconds
[2023-12-28T04:40:20.154+0000] {processor.py:161} INFO - Started process (PID=42492) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.159+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:40:20.160+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:20.160+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.317+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:20.299+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:40:20.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:20.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.318 seconds
[2023-12-28T04:40:47.328+0000] {processor.py:161} INFO - Started process (PID=42538) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.329+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:40:47.331+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:47.330+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.451+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:40:47.439+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:40:47.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:40:47.610+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.286 seconds
[2023-12-28T04:41:20.786+0000] {processor.py:161} INFO - Started process (PID=42594) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:20.821+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:41:20.826+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:41:20.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:21.925+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:41:21.812+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:41:21.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:41:22.048+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.271 seconds
[2023-12-28T04:42:00.955+0000] {processor.py:161} INFO - Started process (PID=42647) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:01.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:42:01.021+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:01.020+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:02.564+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:02.221+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:42:02.567+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:02.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 1.727 seconds
[2023-12-28T04:42:40.334+0000] {processor.py:161} INFO - Started process (PID=42701) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.336+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:42:40.339+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:40.338+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.518+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:42:40.494+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:42:40.522+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:42:40.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.271 seconds
[2023-12-28T04:43:11.610+0000] {processor.py:161} INFO - Started process (PID=42756) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:43:11.616+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:11.615+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.647+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:11.640+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:43:11.649+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:11.686+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.084 seconds
[2023-12-28T04:43:42.633+0000] {processor.py:161} INFO - Started process (PID=42812) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.634+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:43:42.639+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:42.639+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.708+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:43:42.693+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:43:42.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:43:42.821+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.194 seconds
[2023-12-28T04:44:13.337+0000] {processor.py:161} INFO - Started process (PID=42868) to work on /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.339+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2023-12-28T04:44:13.347+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:13.346+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.395+0000] {logging_mixin.py:188} INFO - [2023-12-28T04:44:13.387+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 3, in <module>
    from airflows.operators.bash import BashOperator
ModuleNotFoundError: No module named 'airflows'
[2023-12-28T04:44:13.398+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2023-12-28T04:44:13.444+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/my_dag.py took 0.118 seconds
